# See docs folder for details on implementation

## Site Settings

### Site Information

title: Mary Johnston's The Wanderers
tagline: 
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut eleifend justo. Quisque gravida est a quam ultrices posuere. Suspendisse potenti. Morbi in metus malesuada, facilisis neque at, ornare lorem. Vestibulum augue eros, consectetur nec rhoncus eu, rhoncus at urna.

### Site Structure

baseurl: "/2021-wanderers" # the subpath of your site, e.g. /blog
url: "https://recoveryhub.github.io/" # should not change for Recovery Hub projects

### Contact

email: 
twitter_username: TheCCWH
github_username:  recoveryhub

### Site Setup / Defaults

# Categories listed here must match the 
# categories in defaults, below. 
# The categories are not showing up in the 
# site.categories object  ¯\_(ツ)_/¯

collections: 
  - items
  - test


category_list: ["no_category", "site", "draft", "book", "periodical", "essay"]

defaults:
  - scope:
      path: "_content" # an empty string here means all files in the project
      type: pages
    values:
      layout: default
      category: no_category
  - scope:
      path: "_pages"
      type: pages 
    values:
      layout: default
      category: site
  - scope:
      path: "Source/Draft"
      type: pages
    values:
      layout: default
      category: draft
      # This should work according to this page but does not https://talk.jekyllrb.com/t/creating-custom-permalinks-for-each-post-category/434/4
      # permalink: draft/:title
  - scope:
      path: "book"
      type: pages
    values:
      layout: paginate
      category: book
  - scope:
      path: "periodical"
      type: pages
    values:
      layout: paginate
      category: periodical
  - scope:
      path: "essay"
      type: pages
    values:
      layout: default
      category: essay





# Build settings
theme: minima

plugins:
  - jekyll-feed




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
