# See docs folder for details on implementation

## Site Settings

### Site Information

title: Mary Johnston’s The Wanderers
tagline: 
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus ut eleifend justo. Quisque gravida est a quam ultrices posuere. Suspendisse potenti. Morbi in metus malesuada, facilisis neque at, ornare lorem. Vestibulum augue eros, consectetur nec rhoncus eu, rhoncus at urna.

# If the site title should have HTML in it, e.g. italics around a book title,
# make changes in _includes/site_title_html.html 
# then remove the # from the following line:
html_site_title: true

### Site Structure

baseurl: "/2021-wanderers" # the subpath of your site, e.g. /blog
url: "https://recoveryhub.github.io/" # should not change for Recovery Hub projects

### Banner image

banner_image: assets/images/recovery-hub-banner.jpg
banner_alt_text: Recovery Hub of American Women Writers with quill icon and pages of a book in the background
banner_size: "half" # Available values: "full" (full-width) or "half". Defaults to half if left blank.

### Contact

email: your-email@example.com 
privacy_notice: https://www.siue.edu/web-privacy-notice/

### Social Accounts

twitter_username: TheCCWH
github_username:  recoveryhub

### Sponsors / Organization Logos
# Can be overridden in _includes/footer.html instead

sponsors:
  # copy-paste the following 4 lines for each sponsor
  - sponsor:
    name: Southern Illinois University Edwardsville
    link: https://www.siue.edu/
    logo_path: assets/images/siue.png

  - sponsor:
    name: St. Catherine University
    link: https://www.stkate.edu/
    logo_path: assets/images/stkate.png

  - sponsor: 
    name: National Endowment for the Humanities
    link: https://www.neh.gov/
    logo_path: assets/images/neh.webp

  - sponsor:
    name: The IRIS Center at SIUE
    link: https://iris.siue.edu/
    logo_path: assets/images/iris.png
    
  - sponsor: 
    name: University of Nebraska–Lincoln
    link: https://www.unl.edu/
    logo_path: assets/images/unl.png

### Site Setup / Defaults

# Categories listed here must match the 
# categories in defaults, below. 
# The categories are not showing up in the 
# site.categories object  ¯\_(ツ)_/¯

collections: 
  - items
  - test

category_list: ["no_category", "site", "draft", "book", "periodical", "essay"]

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: default
      category: no_category
  - scope:
      path: "_pages"
      type: pages 
    values:
      layout: default
      category: site
  - scope:
      path: "Source/Draft"
      type: pages
    values:
      layout: default
      category: draft
      # This should work according to this page but does not https://talk.jekyllrb.com/t/creating-custom-permalinks-for-each-post-category/434/4
      # permalink: draft/:title
  - scope:
      path: "book"
      type: pages
    values:
      layout: paginate
      category: book
  - scope:
      path: "periodical"
      type: pages
    values:
      layout: paginate
      category: periodical
  - scope:
      path: "essay"
      type: pages
    values:
      layout: default
      category: essay





### Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag




# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
